services:
  fitplan-app:
    image: oven/bun:1-alpine
    container_name: fitplan-pro
    restart: unless-stopped
    ports:
      - "3019:3000"
    working_dir: /app
    volumes:
      - /tmp/zfsv3/nvme12/17715505757/data/容器/fitplan/data:/app
    command: /bin/sh -c "apk add --no-cache git; if [ ! -f package.json ]; then git clone https://github.com/787676985/fit.git .; fi; if [ ! -d node_modules ]; then bun install; fi; if [ ! -f .next/standalone/server.js ]; then bun run build; fi; node .next/standalone/server.js"
    environment:
      - NODE_ENV=production
      - PORT=3000
